"""add guest_email to table_reservations

Revision ID: f4654c18f14a
Revises: e926ef862ed2
Create Date: 2026-03-12 22:29:22.856325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4654c18f14a'
down_revision: Union[str, None] = 'e926ef862ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_reservations', sa.Column('guest_email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_reservations', 'guest_email')
    # ### end Alembic commands ###
